controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
create_ticket:
    path: /create-ticket
    controller: App\Controller\User\TicketController::create
view_ticket:
    path: /view-ticket
    controller: App\Controller\User\TicketController::view
app_delete_ticket:
    path: /delete-ticket/{id}
    controller: App\Controller\User\TicketController::delete
app_auth_register:
    path: '/auth/register'
    controller: 'App\Controller\Auth\RegisterController::register'
app_auth_login:
    path: '/auth/login'
    controller: 'App\Controller\Auth\LoginController::login'
