controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
create_ticket:
    path: /create-ticket
    controller: App\Controller\User\TicketController::create
view_ticket:
    path: /view-ticket
    controller: App\Controller\User\TicketController::view
